### ISSUE TITLE
Major revisions

### ISSUE THREAD

**Issue by gurdeep330** [raimondilab/precogx#82]
- [x] Rename BW to GPCRdb
- [x] Check if input produces any output after BLASTp with GPCRdb (reports error code 1 to the user)
- [x] Check if any sequence in the input is longer than 1024 (reports error code 2 to the user)
- [x] Rename G-protein groups to Transducers groups
- [x] Split Class B into Class B1 and B2 in the PCA panel (https://github.com/raimondilab/precogx/issues/80#issue-1202103334)
- [x] Rename IUPHAR to GtoPdb; ebBRET to GEMTA; and Shedding to TGF
- [x] Rename GPCRDB as GPCRdb generic numbering system
- [x] Change colour of mutation/WT as requested by Marin (https://github.com/raimondilab/precogx/issues/81#issue-1202196078)
- [x] Replace the '.' by 'x' in the heatmap/sequence and add '0' (https://github.com/raimondilab/precogx/issues/79#issue-1202072120)
- [x] Provide possibility of querying with the GtoPdb nomenclature
